# Generated by Django 5.1 on 2024-08-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Material_Request_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
