# Generated by Django 5.1 on 2024-08-08 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Material_Request_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
    ]
